from __future__ import annotations

from ..levels import EvidenceMaturityLevel, SourceAuthority, SourceScope
from ..schemas import DatasetDefinition, VariableMatrixDefinition


NYC_REQUIRED_DATASET_SEQUENCE = [
    "nyc_dof_property_record",
    "nyc_pluto",
    "nyc_dob_permits",
    "nyc_ll84_benchmarking",
    "nyc_ll97_emissions",
    "nyc_ll97_filing_guidance",
    "nyc_ll97_public_filing_artifact",
]


NYC_DATASETS: dict[str, DatasetDefinition] = {
    "nyc_dof_property_record": DatasetDefinition(
        dataset_key="nyc_dof_property_record",
        display_name="NYC DOF / property record",
        jurisdiction="US-NY-NYC",
        authority=SourceAuthority.HIGH,
        scope=SourceScope.ASSET_LEVEL,
        coverage_variables=["address", "parcel_id", "building_id", "owner", "site_boundary"],
        required_for=["asset identity", "parcel anchor", "jurisdiction anchor"],
        notes="Primary property or parcel anchor for asset identity and BBL/BIN routing.",
    ),
    "nyc_pluto": DatasetDefinition(
        dataset_key="nyc_pluto",
        display_name="NYC PLUTO",
        jurisdiction="US-NY-NYC",
        authority=SourceAuthority.HIGH,
        scope=SourceScope.ASSET_LEVEL,
        coverage_variables=["GFA", "year_built", "asset_type", "owner", "occupancy", "jurisdiction"],
        required_for=["physical substrate", "scale basis", "use classification"],
        notes="Primary NYC land-use and building-attribute dataset.",
    ),
    "nyc_dob_permits": DatasetDefinition(
        dataset_key="nyc_dob_permits",
        display_name="NYC DOB permits / filings",
        jurisdiction="US-NY-NYC",
        authority=SourceAuthority.HIGH,
        scope=SourceScope.ASSET_LEVEL,
        coverage_variables=["major_renovations", "HVAC_type", "boilers", "chillers", "compliance_filing"],
        required_for=["systems clues", "capital activity", "renovation chronology"],
        notes="Permit and filing activity can elevate systems and renovation maturity.",
    ),
    "nyc_ll84_benchmarking": DatasetDefinition(
        dataset_key="nyc_ll84_benchmarking",
        display_name="NYC LL84 benchmarking",
        jurisdiction="US-NY-NYC",
        authority=SourceAuthority.HIGH,
        scope=SourceScope.ASSET_LEVEL,
        coverage_variables=["EUI", "electricity_consumption", "gas_consumption", "utility_bills", "emissions"],
        required_for=["baseline maturity", "consumption screening", "energy scenarios"],
        notes="Primary public dataset for building energy intensity and related annual metrics.",
    ),
    "nyc_ll97_emissions": DatasetDefinition(
        dataset_key="nyc_ll97_emissions",
        display_name="NYC LL97 emissions / compliance context",
        jurisdiction="US-NY-NYC",
        authority=SourceAuthority.HIGH,
        scope=SourceScope.ASSET_LEVEL,
        coverage_variables=["applicable_rule_family", "regulated_floor_area", "emissions", "penalty_rate", "compliance_filing", "compliance_period"],
        required_for=["compliance screening", "penalty exposure", "regulatory readiness"],
        notes="Applies to covered buildings and should be treated as bounded regulatory evidence, not automatic closure.",
    ),
    "nyc_ll97_filing_guidance": DatasetDefinition(
        dataset_key="nyc_ll97_filing_guidance",
        display_name="NYC LL97 filing guidance / BEAM process",
        jurisdiction="US-NY-NYC",
        authority=SourceAuthority.HIGH,
        scope=SourceScope.JURISDICTION_LEVEL,
        coverage_variables=["applicable_rule_family", "compliance_period", "compliance_filing", "compliance_status"],
        required_for=["filing upgrade path", "reporting-process hardening", "public filing-boundary explanation"],
        notes="Official filing guides and FAQs clarify how Article 320/321 filings are submitted, but they are not a public building-level filing registry.",
    ),
    "nyc_ll97_public_filing_artifact": DatasetDefinition(
        dataset_key="nyc_ll97_public_filing_artifact",
        display_name="NYC LL97 public filing artifact candidate",
        jurisdiction="US-NY-NYC",
        authority=SourceAuthority.HIGH,
        scope=SourceScope.ASSET_LEVEL,
        coverage_variables=["compliance_filing", "compliance_status"],
        required_for=["filing hardening", "compliance path strengthening"],
        notes="Only use when a public asset-specific filing artifact or Article 321 submission package is directly observed from authority or owner-published sources.",
    ),
}


NYC_BUILDING_VARIABLE_MATRIX: dict[str, VariableMatrixDefinition] = {
    "GFA": VariableMatrixDefinition(
        variable_name="GFA",
        level_definitions={
            EvidenceMaturityLevel.L0: "Not observed.",
            EvidenceMaturityLevel.L1: "Scale proxy or inferred area only.",
            EvidenceMaturityLevel.L2: "Listing or brochure area.",
            EvidenceMaturityLevel.L3: "PLUTO / assessor / official property record.",
            EvidenceMaturityLevel.L4: "Verified official or field-hardened area basis.",
        },
        outputs_allowed={
            EvidenceMaturityLevel.L0: ["missing-field flag", "evidence request"],
            EvidenceMaturityLevel.L1: ["qualitative scale framing"],
            EvidenceMaturityLevel.L2: ["preliminary scale-based scenario bounds"],
            EvidenceMaturityLevel.L3: ["numeric EUI and compliance screening inputs"],
            EvidenceMaturityLevel.L4: ["strongest bounded scale-dependent claims"],
        },
        outputs_forbidden={
            EvidenceMaturityLevel.L0: ["numeric EUI", "LL97 penalty estimate", "area-based ROI"],
            EvidenceMaturityLevel.L1: ["decision-grade compliance math"],
            EvidenceMaturityLevel.L2: ["verification-grade area claims"],
            EvidenceMaturityLevel.L3: ["unbounded extrapolation beyond recorded scope"],
            EvidenceMaturityLevel.L4: [],
        },
        upgrade_evidence=["PLUTO lookup", "assessor record", "official owner disclosure", "verified survey or field basis"],
        decisions_unlocked={
            EvidenceMaturityLevel.L0: ["request evidence only"],
            EvidenceMaturityLevel.L1: ["screening only"],
            EvidenceMaturityLevel.L2: ["preliminary scenario framing"],
            EvidenceMaturityLevel.L3: ["compliance screening", "ROI support with other variables"],
            EvidenceMaturityLevel.L4: ["strongest scale-based decision support"],
        },
    ),
    "EUI": VariableMatrixDefinition(
        variable_name="EUI",
        level_definitions={
            EvidenceMaturityLevel.L0: "Missing.",
            EvidenceMaturityLevel.L1: "Benchmark-only or archetype intensity.",
            EvidenceMaturityLevel.L2: "Estimated or owner-disclosed intensity.",
            EvidenceMaturityLevel.L3: "LL84 or bill-derived public asset-specific intensity.",
            EvidenceMaturityLevel.L4: "Validated normalized baseline.",
        },
        outputs_allowed={
            EvidenceMaturityLevel.L0: ["missing-field flag", "benchmark request"],
            EvidenceMaturityLevel.L1: ["scenario screening", "plausibility framing"],
            EvidenceMaturityLevel.L2: ["directional range with explicit caveat"],
            EvidenceMaturityLevel.L3: ["asset-specific baseline screening", "scenario-based ROI support"],
            EvidenceMaturityLevel.L4: ["strongest bounded performance claims"],
        },
        outputs_forbidden={
            EvidenceMaturityLevel.L0: ["savings claim", "numeric compliance estimate"],
            EvidenceMaturityLevel.L1: ["asset savings claim", "local truth posture"],
            EvidenceMaturityLevel.L2: ["verification-grade baseline"],
            EvidenceMaturityLevel.L3: ["verified savings without validation protocol"],
            EvidenceMaturityLevel.L4: [],
        },
        upgrade_evidence=["LL84 disclosure", "utility bills", "weather normalization", "baseline hardening"],
        decisions_unlocked={
            EvidenceMaturityLevel.L0: ["evidence request"],
            EvidenceMaturityLevel.L1: ["scenario screening"],
            EvidenceMaturityLevel.L2: ["preliminary ranges"],
            EvidenceMaturityLevel.L3: ["stronger screening and ROI scenarios"],
            EvidenceMaturityLevel.L4: ["strongest bounded baseline-dependent decisions"],
        },
    ),
    "emissions": VariableMatrixDefinition(
        variable_name="emissions",
        level_definitions={
            EvidenceMaturityLevel.L0: "Unknown emissions basis.",
            EvidenceMaturityLevel.L1: "Proxy emissions basis.",
            EvidenceMaturityLevel.L2: "Estimated asset-specific emissions.",
            EvidenceMaturityLevel.L3: "LL84/LL97 public record.",
            EvidenceMaturityLevel.L4: "Validated filing or audited emissions basis.",
        },
        outputs_allowed={
            EvidenceMaturityLevel.L0: ["missing-field flag"],
            EvidenceMaturityLevel.L1: ["regulatory plausibility only"],
            EvidenceMaturityLevel.L2: ["bounded exposure screening"],
            EvidenceMaturityLevel.L3: ["LL97 scenario screening", "penalty scenario support"],
            EvidenceMaturityLevel.L4: ["strongest bounded compliance posture"],
        },
        outputs_forbidden={
            EvidenceMaturityLevel.L0: ["penalty estimate", "compliance posture"],
            EvidenceMaturityLevel.L1: ["numeric closure"],
            EvidenceMaturityLevel.L2: ["final compliance conclusion"],
            EvidenceMaturityLevel.L3: ["verified compliance without filing context"],
            EvidenceMaturityLevel.L4: [],
        },
        upgrade_evidence=["LL84/LL97 records", "official filing", "validated emissions factor and baseline"],
        decisions_unlocked={
            EvidenceMaturityLevel.L0: ["request evidence"],
            EvidenceMaturityLevel.L1: ["regulatory screening"],
            EvidenceMaturityLevel.L2: ["bounded compliance scenario"],
            EvidenceMaturityLevel.L3: ["compliance investment screening"],
            EvidenceMaturityLevel.L4: ["strongest bounded regulatory decisions"],
        },
    ),
    "tariff_class": VariableMatrixDefinition(
        variable_name="tariff_class",
        level_definitions={
            EvidenceMaturityLevel.L0: "Unknown tariff.",
            EvidenceMaturityLevel.L1: "Regional tariff proxy.",
            EvidenceMaturityLevel.L2: "Estimated service class.",
            EvidenceMaturityLevel.L3: "Bill-based or utility-backed tariff.",
            EvidenceMaturityLevel.L4: "Contract-validated tariff and rider basis.",
        },
        outputs_allowed={
            EvidenceMaturityLevel.L0: ["no numeric tariff claim"],
            EvidenceMaturityLevel.L1: ["directional cost framing"],
            EvidenceMaturityLevel.L2: ["preliminary rate range"],
            EvidenceMaturityLevel.L3: ["scenario-based cost and ROI"],
            EvidenceMaturityLevel.L4: ["strongest bounded cost claims"],
        },
        outputs_forbidden={
            EvidenceMaturityLevel.L0: ["numeric ROI"],
            EvidenceMaturityLevel.L1: ["closed economics"],
            EvidenceMaturityLevel.L2: ["contract-grade cost claim"],
            EvidenceMaturityLevel.L3: ["unbounded extrapolation"],
            EvidenceMaturityLevel.L4: [],
        },
        upgrade_evidence=["utility bills", "tariff sheet", "contract/rider review"],
        decisions_unlocked={
            EvidenceMaturityLevel.L0: ["narrative exposure only"],
            EvidenceMaturityLevel.L1: ["directional screening"],
            EvidenceMaturityLevel.L2: ["preliminary ROI range"],
            EvidenceMaturityLevel.L3: ["scenario ROI"],
            EvidenceMaturityLevel.L4: ["strongest bounded economics"],
        },
    ),
    "HVAC_type": VariableMatrixDefinition(
        variable_name="HVAC_type",
        level_definitions={
            EvidenceMaturityLevel.L0: "Unknown.",
            EvidenceMaturityLevel.L1: "Archetype only.",
            EvidenceMaturityLevel.L2: "Listing, brochure, or permit clue.",
            EvidenceMaturityLevel.L3: "Engineering, O&M, or permit-backed system basis.",
            EvidenceMaturityLevel.L4: "Field-validated system basis.",
        },
        outputs_allowed={
            EvidenceMaturityLevel.L0: ["missing-field flag"],
            EvidenceMaturityLevel.L1: ["system hypothesis"],
            EvidenceMaturityLevel.L2: ["preliminary retrofit family screening"],
            EvidenceMaturityLevel.L3: ["stronger measure selection", "ROI scenario support"],
            EvidenceMaturityLevel.L4: ["strongest bounded system claims"],
        },
        outputs_forbidden={
            EvidenceMaturityLevel.L0: ["retrofit recommendation"],
            EvidenceMaturityLevel.L1: ["system-specific CAPEX claim"],
            EvidenceMaturityLevel.L2: ["verification-grade system recommendation"],
            EvidenceMaturityLevel.L3: ["field-verified language without field evidence"],
            EvidenceMaturityLevel.L4: [],
        },
        upgrade_evidence=["DOB permits", "MEP schedule", "engineering report", "field survey"],
        decisions_unlocked={
            EvidenceMaturityLevel.L0: ["request system inventory"],
            EvidenceMaturityLevel.L1: ["archetype screening"],
            EvidenceMaturityLevel.L2: ["measure family screening"],
            EvidenceMaturityLevel.L3: ["validate-first retrofit decision"],
            EvidenceMaturityLevel.L4: ["strongest bounded implementation support"],
        },
    ),
    "compliance_filing": VariableMatrixDefinition(
        variable_name="compliance_filing",
        level_definitions={
            EvidenceMaturityLevel.L0: "No filing observed.",
            EvidenceMaturityLevel.L1: "Rule-family expectation only.",
            EvidenceMaturityLevel.L2: "Preliminary filing clue or owner statement.",
            EvidenceMaturityLevel.L3: "Official filing located.",
            EvidenceMaturityLevel.L4: "Validated filing with reviewed scope.",
        },
        outputs_allowed={
            EvidenceMaturityLevel.L0: ["missing-filing request"],
            EvidenceMaturityLevel.L1: ["screening only"],
            EvidenceMaturityLevel.L2: ["bounded trigger plausibility"],
            EvidenceMaturityLevel.L3: ["stronger preliminary compliance posture"],
            EvidenceMaturityLevel.L4: ["strongest bounded compliance posture"],
        },
        outputs_forbidden={
            EvidenceMaturityLevel.L0: ["compliance conclusion"],
            EvidenceMaturityLevel.L1: ["filing-backed language"],
            EvidenceMaturityLevel.L2: ["closure"],
            EvidenceMaturityLevel.L3: ["legal conclusion outside filing scope"],
            EvidenceMaturityLevel.L4: [],
        },
        upgrade_evidence=[
            "official filing pdf or BEAM export",
            "validated filing metadata",
            "independent review",
        ],
        decisions_unlocked={
            EvidenceMaturityLevel.L0: ["request filing"],
            EvidenceMaturityLevel.L1: ["screen only"],
            EvidenceMaturityLevel.L2: ["validate-first compliance decision"],
            EvidenceMaturityLevel.L3: ["preliminary compliance path"],
            EvidenceMaturityLevel.L4: ["strongest bounded compliance path"],
        },
    ),
    "CAPEX": VariableMatrixDefinition(
        variable_name="CAPEX",
        level_definitions={
            EvidenceMaturityLevel.L0: "Not admissible.",
            EvidenceMaturityLevel.L1: "Benchmark cost only.",
            EvidenceMaturityLevel.L2: "Preliminary cost range.",
            EvidenceMaturityLevel.L3: "Vendor quote or engineering estimate.",
            EvidenceMaturityLevel.L4: "Contract or validated cost basis.",
        },
        outputs_allowed={
            EvidenceMaturityLevel.L0: ["no numeric CAPEX"],
            EvidenceMaturityLevel.L1: ["directional economics only"],
            EvidenceMaturityLevel.L2: ["preliminary ROI range"],
            EvidenceMaturityLevel.L3: ["scenario-based ROI"],
            EvidenceMaturityLevel.L4: ["strongest bounded financial support"],
        },
        outputs_forbidden={
            EvidenceMaturityLevel.L0: ["ROI"],
            EvidenceMaturityLevel.L1: ["investment-grade economics"],
            EvidenceMaturityLevel.L2: ["contract-grade budget language"],
            EvidenceMaturityLevel.L3: ["verified cost without contract"],
            EvidenceMaturityLevel.L4: [],
        },
        upgrade_evidence=["cost benchmark", "engineering estimate", "vendor quote", "contract"],
        decisions_unlocked={
            EvidenceMaturityLevel.L0: ["evidence request"],
            EvidenceMaturityLevel.L1: ["directional screening"],
            EvidenceMaturityLevel.L2: ["validate-first economics"],
            EvidenceMaturityLevel.L3: ["scenario-based decision support"],
            EvidenceMaturityLevel.L4: ["strongest bounded commitment support"],
        },
    ),
    "ROI": VariableMatrixDefinition(
        variable_name="ROI",
        level_definitions={
            EvidenceMaturityLevel.L0: "Not admissible.",
            EvidenceMaturityLevel.L1: "Directional economics only.",
            EvidenceMaturityLevel.L2: "Preliminary ROI range.",
            EvidenceMaturityLevel.L3: "Scenario-based ROI.",
            EvidenceMaturityLevel.L4: "Strong bounded ROI support.",
        },
        outputs_allowed={
            EvidenceMaturityLevel.L0: ["no ROI"],
            EvidenceMaturityLevel.L1: ["directional economics"],
            EvidenceMaturityLevel.L2: ["low-confidence ROI range"],
            EvidenceMaturityLevel.L3: ["scenario ROI and downside/upside framing"],
            EvidenceMaturityLevel.L4: ["strongest bounded return support"],
        },
        outputs_forbidden={
            EvidenceMaturityLevel.L0: ["numeric ROI"],
            EvidenceMaturityLevel.L1: ["closed business case"],
            EvidenceMaturityLevel.L2: ["bankability"],
            EvidenceMaturityLevel.L3: ["verified ROI without hardening"],
            EvidenceMaturityLevel.L4: ["universal extrapolation"],
        },
        upgrade_evidence=["bill-backed baseline", "tariff basis", "control boundary", "CAPEX hardening", "validated savings method"],
        decisions_unlocked={
            EvidenceMaturityLevel.L0: ["financial exposure narrative only"],
            EvidenceMaturityLevel.L1: ["screening"],
            EvidenceMaturityLevel.L2: ["preliminary validate-first capital framing"],
            EvidenceMaturityLevel.L3: ["stronger scenario-based TAD support"],
            EvidenceMaturityLevel.L4: ["strongest bounded implementation support"],
        },
    ),
}


def get_nyc_building_domain_pack() -> dict[str, object]:
    return {
        "jurisdiction": "US-NY-NYC",
        "datasets": {key: value.to_dict() for key, value in NYC_DATASETS.items()},
        "required_dataset_sequence": list(NYC_REQUIRED_DATASET_SEQUENCE),
        "variable_matrix": {key: value.to_dict() for key, value in NYC_BUILDING_VARIABLE_MATRIX.items()},
        "benchmark_families": [
            "CBECS_office",
            "CBECS_multifamily",
            "ENERGY_STAR_building_type",
            "ASHRAE_climate_zone_4A",
        ],
        "required_identity_anchors": [
            "BBL or BIN match",
            "PLUTO or DOF property record",
            "address normalization",
        ],
    }
