from .asset_type_router import ASSET_TYPE_ROUTES, route_for_asset_type
from .critical_fields import (
    ASSET_TYPE_CRITICAL_FIELDS,
    BASE_CRITICAL_FIELDS,
    DEFAULT_MAX_MISSING_CRITICAL_FIELDS,
    critical_fields_for_asset_type,
    default_evidence_gating_plan,
)
from .jurisdiction_resolver import resolve_us_jurisdiction, routing_keys_for_resolution
from .report_switching import derive_report_type_switch
from .routing_engine import (
    build_critical_field_contract,
    build_routing_bundle,
    build_target_classification_from_upstream,
)
from .schemas import (
    AccessMethod,
    AssetTypeRoute,
    AssetType,
    AuthorityTier,
    CriticalFieldRequirement,
    CriticalFieldStatus,
    DecisionType,
    EvidenceGatingPlan,
    JurisdictionClass,
    JurisdictionResolution,
    ReportTypeSwitchRecommendation,
    RoutingPriority,
    SourceLayer,
    SourceRegistryRecord,
    SourceRoutingEntry,
    SourceRoutingPlan,
    TargetClassification,
    TargetClassificationResult,
)
from .source_registry import (
    ALL_SOURCE_REGISTRY,
    all_source_registry_records,
    build_source_routing_plan,
    registry_records_for_route,
    source_matrix_rows,
)
from .target_taxonomy import (
    REPORT_SWITCH_BY_TARGET_CLASS,
    TARGET_TYPE_ALIASES,
    TECHNICAL_ROUTE_ELIGIBLE,
    make_target_classification_result,
    normalize_asset_type,
    normalize_target_classification,
    technical_scraping_allowed_for_target_class,
)

__all__ = [
    "ALL_SOURCE_REGISTRY",
    "ASSET_TYPE_ROUTES",
    "ASSET_TYPE_CRITICAL_FIELDS",
    "BASE_CRITICAL_FIELDS",
    "DEFAULT_MAX_MISSING_CRITICAL_FIELDS",
    "AccessMethod",
    "AssetTypeRoute",
    "AssetType",
    "AuthorityTier",
    "CriticalFieldRequirement",
    "CriticalFieldStatus",
    "DecisionType",
    "EvidenceGatingPlan",
    "JurisdictionClass",
    "JurisdictionResolution",
    "REPORT_SWITCH_BY_TARGET_CLASS",
    "ReportTypeSwitchRecommendation",
    "RoutingPriority",
    "SourceLayer",
    "SourceRegistryRecord",
    "SourceRoutingEntry",
    "SourceRoutingPlan",
    "TARGET_TYPE_ALIASES",
    "TECHNICAL_ROUTE_ELIGIBLE",
    "TargetClassification",
    "TargetClassificationResult",
    "all_source_registry_records",
    "build_critical_field_contract",
    "build_routing_bundle",
    "build_source_routing_plan",
    "build_target_classification_from_upstream",
    "critical_fields_for_asset_type",
    "derive_report_type_switch",
    "default_evidence_gating_plan",
    "make_target_classification_result",
    "normalize_asset_type",
    "normalize_target_classification",
    "registry_records_for_route",
    "resolve_us_jurisdiction",
    "route_for_asset_type",
    "routing_keys_for_resolution",
    "source_matrix_rows",
    "technical_scraping_allowed_for_target_class",
]
