from __future__ import annotations

from .levels import SourceScope
from .schemas import VariableCatalogEntry


def _entry(
    variable_name: str,
    variable_family: str,
    description: str,
    observed_kind: str,
    criticality: str,
    default_scope: SourceScope,
    unit_hint: str | None = None,
    dependencies: list[str] | None = None,
    decision_relevance: list[str] | None = None,
) -> VariableCatalogEntry:
    return VariableCatalogEntry(
        variable_name=variable_name,
        variable_family=variable_family,
        description=description,
        observed_kind=observed_kind,
        criticality=criticality,
        default_scope=default_scope,
        unit_hint=unit_hint,
        dependencies=dependencies or [],
        decision_relevance=decision_relevance or [],
    )


VARIABLE_CATALOG: dict[str, VariableCatalogEntry] = {
    "address": _entry("address", "identity", "Normalized target address.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["identity", "report_type"]),
    "asset_name": _entry("asset_name", "identity", "Resolved property or facility name.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["identity", "report_type"]),
    "asset_type": _entry("asset_type", "identity", "Resolved asset type or facility class.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["identity", "benchmark_routing", "report_type"]),
    "owner": _entry("owner", "identity", "Current owner of the target asset.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["identity", "data_request"]),
    "operator": _entry("operator", "identity", "Current operating entity or site operator.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["identity", "control_boundary"]),
    "parcel_id": _entry("parcel_id", "identity", "Parcel, lot, or assessor identifier.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["identity", "jurisdiction"]),
    "building_id": _entry("building_id", "identity", "Jurisdiction-specific building identifier such as BIN/BBL.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["identity", "nyc_dataset_routing"]),
    "site_boundary": _entry("site_boundary", "identity", "Spatial boundary of the evaluated asset or site.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["control_boundary", "report_type"]),
    "ownership_scope": _entry("ownership_scope", "identity", "Scope of ownership versus site footprint.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["control_boundary", "finance"]),
    "entity_scope": _entry("entity_scope", "identity", "Owner or issuer scope associated with the target.", "observed", "high", SourceScope.ENTITY_LEVEL, decision_relevance=["issuer_context"]),
    "asset_vs_entity_classification": _entry("asset_vs_entity_classification", "identity", "Target classification between asset, HQ, mailing, or ambiguous.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["identity", "report_type", "tad"]),
    "jurisdiction": _entry("jurisdiction", "regulatory", "Applicable city/state/county jurisdiction.", "observed", "critical", SourceScope.JURISDICTION_LEVEL, decision_relevance=["compliance", "report_type"]),
    "GFA": _entry("GFA", "physical", "Gross floor area or equivalent scale basis.", "observed", "critical", SourceScope.ASSET_LEVEL, unit_hint="sqft", decision_relevance=["EUI", "compliance", "roi"]),
    "rentable_area": _entry("rentable_area", "physical", "Rentable or leasable area.", "observed", "high", SourceScope.ASSET_LEVEL, unit_hint="sqft", decision_relevance=["underwriting"]),
    "floor_count": _entry("floor_count", "physical", "Number of floors or levels.", "observed", "medium", SourceScope.ASSET_LEVEL),
    "site_area": _entry("site_area", "physical", "Land or site area.", "observed", "medium", SourceScope.ASSET_LEVEL, unit_hint="sqft"),
    "year_built": _entry("year_built", "physical", "Original year built.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["systems", "benchmark_routing"]),
    "major_renovations": _entry("major_renovations", "physical", "Major renovation dates or scopes.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["systems", "capex"]),
    "construction_type": _entry("construction_type", "physical", "Construction or enclosure typology.", "observed", "medium", SourceScope.ASSET_LEVEL),
    "structural_constraints": _entry("structural_constraints", "physical", "Structural constraints relevant to interventions.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["retrofit"]),
    "operating_schedule": _entry("operating_schedule", "operational", "Hours, seasonality, or runtime pattern.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["baseline", "roi", "process"]),
    "occupancy": _entry("occupancy", "operational", "Occupancy or utilization basis.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["baseline", "underwriting"]),
    "throughput": _entry("throughput", "operational", "Production or logistics throughput.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["process", "roi"]),
    "tenant_control_boundary": _entry("tenant_control_boundary", "operational", "Boundary of tenant operational control.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["roi", "savings", "process"]),
    "owner_control_boundary": _entry("owner_control_boundary", "operational", "Boundary of owner control for systems and measures.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["roi", "tad"]),
    "process_flow": _entry("process_flow", "operational", "Workflow or process description for industrial assets.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["process"]),
    "downtime_profile": _entry("downtime_profile", "operational", "Operational downtime pattern and outage tolerance.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["retrofit", "process"]),
    "load_driver": _entry("load_driver", "operational", "Primary operational load driver.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["baseline", "process"]),
    "operational_variability": _entry("operational_variability", "operational", "Variation across shifts, seasons, or campaigns.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["baseline"]),
    "utility_bills": _entry("utility_bills", "energy", "Utility bill series covering the baseline period.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["baseline", "roi", "compliance"]),
    "interval_meter_data": _entry("interval_meter_data", "energy", "Interval metering or load profile data.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["baseline", "savings"]),
    "EUI": _entry("EUI", "energy", "Energy use intensity or equivalent intensity metric.", "derived", "critical", SourceScope.DERIVED_INTERNAL, unit_hint="kBtu/sqft", dependencies=["utility_bills", "GFA"], decision_relevance=["baseline", "savings", "compliance"]),
    "primary_fuel": _entry("primary_fuel", "energy", "Primary on-site fuel.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["emissions", "compliance"]),
    "secondary_fuel": _entry("secondary_fuel", "energy", "Secondary or backup fuel.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["emissions"]),
    "electricity_utility": _entry("electricity_utility", "energy", "Electric utility territory or service provider.", "observed", "medium", SourceScope.JURISDICTION_LEVEL, decision_relevance=["tariff_class", "energy_cost"]),
    "gas_utility": _entry("gas_utility", "energy", "Gas utility territory or service provider.", "observed", "medium", SourceScope.JURISDICTION_LEVEL, decision_relevance=["tariff_class", "energy_cost"]),
    "electricity_consumption": _entry("electricity_consumption", "energy", "Electricity use over baseline period.", "observed", "high", SourceScope.ASSET_LEVEL, unit_hint="kWh", decision_relevance=["baseline", "roi"]),
    "gas_consumption": _entry("gas_consumption", "energy", "Gas use over baseline period.", "observed", "high", SourceScope.ASSET_LEVEL, unit_hint="therms", decision_relevance=["baseline", "compliance"]),
    "steam_consumption": _entry("steam_consumption", "energy", "Steam use over baseline period.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["baseline"]),
    "demand_charges": _entry("demand_charges", "energy", "Demand-charge component of energy cost.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["roi"]),
    "tariff_class": _entry("tariff_class", "energy", "Applicable tariff or service class.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["roi", "financial_exposure"]),
    "load_profile": _entry("load_profile", "energy", "Profile of load across time.", "derived", "high", SourceScope.DERIVED_INTERNAL, dependencies=["interval_meter_data"], decision_relevance=["savings", "process"]),
    "peak_demand": _entry("peak_demand", "energy", "Peak demand metric.", "derived", "high", SourceScope.DERIVED_INTERNAL, dependencies=["interval_meter_data"], decision_relevance=["roi"]),
    "baseline_period": _entry("baseline_period", "energy", "Representative period for baseline calculations.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["roi", "savings"]),
    "HVAC_type": _entry("HVAC_type", "systems", "Primary HVAC system type.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["roi", "retrofit"]),
    "BMS_presence": _entry("BMS_presence", "systems", "Presence of building management or automation system.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["savings"]),
    "controls_architecture": _entry("controls_architecture", "systems", "Controls architecture and automation boundary.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["savings", "process"]),
    "refrigeration_system": _entry("refrigeration_system", "systems", "Refrigeration system definition.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["cold_chain", "food_processing"]),
    "boilers": _entry("boilers", "systems", "Boiler inventory or system basis.", "observed", "medium", SourceScope.ASSET_LEVEL),
    "chillers": _entry("chillers", "systems", "Chiller inventory or system basis.", "observed", "medium", SourceScope.ASSET_LEVEL),
    "compressed_air": _entry("compressed_air", "systems", "Compressed-air system basis.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["industrial_process"]),
    "metering_boundary": _entry("metering_boundary", "systems", "Metering boundary for the evaluated asset.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["baseline", "roi", "compliance"]),
    "submetering": _entry("submetering", "systems", "Submeter presence and granularity.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["baseline", "tenant_control"]),
    "maintenance_history": _entry("maintenance_history", "systems", "Historical maintenance data.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["reliability"]),
    "reliability_history": _entry("reliability_history", "systems", "Failure or reliability history.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["retrofit", "process"]),
    "energy_cost": _entry("energy_cost", "finance", "Observed energy cost basis.", "derived", "critical", SourceScope.DERIVED_INTERNAL, dependencies=["utility_bills", "tariff_class"], decision_relevance=["roi", "exposure"]),
    "CAPEX": _entry("CAPEX", "finance", "Capital cost estimate for a candidate measure.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["roi", "tad"]),
    "OPEX": _entry("OPEX", "finance", "Operating expenditure basis.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["roi"]),
    "savings": _entry("savings", "finance", "Energy or cost savings estimate.", "derived", "critical", SourceScope.DERIVED_INTERNAL, dependencies=["utility_bills", "load_profile", "candidate_measure", "owner_control_boundary"], decision_relevance=["roi", "tad"]),
    "ROI": _entry("ROI", "finance", "Return-on-investment estimate.", "derived", "critical", SourceScope.DERIVED_INTERNAL, dependencies=["savings", "CAPEX", "owner_control_boundary"], decision_relevance=["roi", "tad"]),
    "payback": _entry("payback", "finance", "Simple or bounded payback estimate.", "derived", "high", SourceScope.DERIVED_INTERNAL, dependencies=["savings", "CAPEX"], decision_relevance=["roi"]),
    "NPV": _entry("NPV", "finance", "Net present value estimate.", "derived", "high", SourceScope.DERIVED_INTERNAL, dependencies=["savings", "CAPEX", "financing_cost"], decision_relevance=["finance"]),
    "IRR": _entry("IRR", "finance", "Internal rate of return estimate.", "derived", "high", SourceScope.DERIVED_INTERNAL, dependencies=["savings", "CAPEX", "baseline_period"], decision_relevance=["finance"]),
    "DSCR": _entry("DSCR", "finance", "Debt service coverage ratio.", "derived", "medium", SourceScope.DERIVED_INTERNAL, dependencies=["NOI", "debt_schedule"]),
    "LTV": _entry("LTV", "finance", "Loan-to-value ratio.", "derived", "medium", SourceScope.DERIVED_INTERNAL, dependencies=["debt_schedule"]),
    "NOI": _entry("NOI", "finance", "Net operating income basis.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["finance"]),
    "financing_cost": _entry("financing_cost", "finance", "Cost of financing or discount rate basis.", "observed", "medium", SourceScope.ENTITY_LEVEL, decision_relevance=["finance"]),
    "debt_schedule": _entry("debt_schedule", "finance", "Debt schedule or debt obligation context.", "observed", "medium", SourceScope.ENTITY_LEVEL, decision_relevance=["finance"]),
    "carbon_cost": _entry("carbon_cost", "finance", "Carbon-cost assumption or observed cost basis.", "derived", "medium", SourceScope.DERIVED_INTERNAL, dependencies=["emissions", "penalty_rate"], decision_relevance=["compliance", "finance"]),
    "penalty_exposure": _entry("penalty_exposure", "finance", "Exposure to penalties or regulatory cost.", "derived", "critical", SourceScope.DERIVED_INTERNAL, dependencies=["jurisdiction", "applicable_rule_family", "regulated_floor_area", "emissions", "penalty_rate"], decision_relevance=["compliance", "tad"]),
    "value_of_information": _entry("value_of_information", "finance", "Value of resolving key evidence bottlenecks.", "derived", "high", SourceScope.DERIVED_INTERNAL, dependencies=["ROI", "penalty_exposure"], decision_relevance=["tad"]),
    "applicable_rule_family": _entry("applicable_rule_family", "regulatory", "Applicable rule or regulatory family.", "observed", "critical", SourceScope.JURISDICTION_LEVEL, decision_relevance=["compliance", "report_type"]),
    "trigger_fields": _entry("trigger_fields", "regulatory", "Trigger inputs for a rule family.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["compliance"]),
    "regulated_floor_area": _entry("regulated_floor_area", "regulatory", "Floor area relevant to rule applicability.", "derived", "critical", SourceScope.DERIVED_INTERNAL, dependencies=["GFA", "occupancy"], decision_relevance=["compliance", "penalty_exposure"]),
    "emissions": _entry("emissions", "regulatory", "Observed or estimated asset emissions basis.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["compliance", "penalty_exposure", "carbon_cost"]),
    "emissions_factor": _entry("emissions_factor", "regulatory", "Applicable emissions factor.", "observed", "high", SourceScope.JURISDICTION_LEVEL, decision_relevance=["compliance"]),
    "benchmarking_requirement": _entry("benchmarking_requirement", "regulatory", "Whether disclosure/benchmarking is required.", "observed", "high", SourceScope.JURISDICTION_LEVEL, decision_relevance=["compliance"]),
    "compliance_filing": _entry("compliance_filing", "regulatory", "Official filing or reporting artifact.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["compliance"]),
    "penalty_rate": _entry("penalty_rate", "regulatory", "Penalty-rate basis from applicable rule.", "observed", "high", SourceScope.JURISDICTION_LEVEL, decision_relevance=["penalty_exposure"]),
    "compliance_period": _entry("compliance_period", "regulatory", "Applicable compliance period.", "observed", "medium", SourceScope.JURISDICTION_LEVEL, decision_relevance=["compliance"]),
    "compliance_status": _entry("compliance_status", "regulatory", "Status of compliance supported by evidence.", "derived", "critical", SourceScope.DERIVED_INTERNAL, dependencies=["applicable_rule_family", "trigger_fields", "compliance_filing"], decision_relevance=["compliance", "tad"]),
    "candidate_measure": _entry("candidate_measure", "intervention", "Candidate measure or action family.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["roi", "tad"]),
    "retrofit_type": _entry("retrofit_type", "intervention", "Retrofit or engineering intervention type.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["roi", "tad"]),
    "operational_change": _entry("operational_change", "intervention", "Candidate operational change.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["process", "tad"]),
    "implementation_complexity": _entry("implementation_complexity", "intervention", "Complexity of implementation.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["tad"]),
    "disruption_risk": _entry("disruption_risk", "intervention", "Operational disruption risk.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["tad"]),
    "reversibility": _entry("reversibility", "intervention", "Reversibility of the measure.", "observed", "medium", SourceScope.ASSET_LEVEL, decision_relevance=["tad"]),
    "downtime_required": _entry("downtime_required", "intervention", "Required downtime for implementation.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["tad", "process"]),
    "affected_systems": _entry("affected_systems", "intervention", "Systems touched by the measure.", "observed", "high", SourceScope.ASSET_LEVEL, decision_relevance=["roi", "tad"]),
    "stakeholder_control": _entry("stakeholder_control", "intervention", "Control or approval boundary for action.", "observed", "critical", SourceScope.ASSET_LEVEL, decision_relevance=["tad", "roi"]),
}


def get_variable_catalog_entry(variable_name: str) -> VariableCatalogEntry | None:
    return VARIABLE_CATALOG.get(variable_name)
