from __future__ import annotations

from ..schemas import (
    AccessMethod,
    AssetType,
    AuthorityTier,
    RoutingPriority,
    SourceLayer,
    SourceRegistryRecord,
    SourceRoutingEntry,
)


def _record(
    asset_type: AssetType,
    *,
    source_key: str,
    source_name: str,
    layer: SourceLayer,
    access_method: AccessMethod,
    fields: list[str],
    authority: AuthorityTier,
    update_frequency: str,
    use: str,
    limitations: str,
    priority: RoutingPriority,
    disallowed_as_substitute_for: list[str] | None = None,
) -> SourceRegistryRecord:
    return SourceRegistryRecord(
        jurisdiction="US-INDUSTRIAL",
        asset_type=asset_type,
        source=SourceRoutingEntry(
            source_key=source_key,
            source_name=source_name,
            layer=layer,
            access_method=access_method,
            fields=fields,
            authority=authority,
            update_frequency=update_frequency,
            use=use,
            limitations=limitations,
            priority=priority,
            disallowed_as_substitute_for=list(disallowed_as_substitute_for or []),
        ),
    )


INDUSTRIAL_CROSS_STATE_SOURCE_REGISTRY: list[SourceRegistryRecord] = [
    _record(
        AssetType.INDUSTRIAL_FACILITY,
        source_key="state_environmental_agency_permits",
        source_name="State environmental agency permits and emissions records",
        layer=SourceLayer.INDUSTRIAL_ENVIRONMENT,
        access_method=AccessMethod.PORTAL,
        fields=["permit_ids", "regulated_equipment", "emissions", "facility_name"],
        authority=AuthorityTier.HIGH,
        update_frequency="continuous",
        use="state-level industrial permit and emissions anchor",
        limitations="Permit registry is not a full process map or utility baseline.",
        priority=RoutingPriority.MANDATORY,
        disallowed_as_substitute_for=["full_process_inventory", "utility_bills"],
    ),
    _record(
        AssetType.INDUSTRIAL_FACILITY,
        source_key="county_assessor_or_appraisal_property_record",
        source_name="County assessor or appraisal property record",
        layer=SourceLayer.PROPERTY,
        access_method=AccessMethod.PORTAL,
        fields=["address", "owner", "parcel_id", "site_area_or_improvements"],
        authority=AuthorityTier.HIGH,
        update_frequency="annual or continuous",
        use="cross-state property anchor when site routing begins",
        limitations="Property anchor only.",
        priority=RoutingPriority.MANDATORY,
        disallowed_as_substitute_for=["brochure", "issuer_page"],
    ),
    _record(
        AssetType.INDUSTRIAL_FACILITY,
        source_key="epa_ghgrp_emitters",
        source_name="EPA GHGRP facility emissions",
        layer=SourceLayer.INDUSTRIAL_ENVIRONMENT,
        access_method=AccessMethod.API,
        fields=["facility_name", "co2e_emissions", "reporting_year", "source_category"],
        authority=AuthorityTier.HIGH,
        update_frequency="annual",
        use="federal large-emitter context when the facility is covered",
        limitations="Only covered facilities appear; missing record is not proof of low emissions.",
        priority=RoutingPriority.HIGH_PRIORITY,
        disallowed_as_substitute_for=["site_level_energy_balance", "utility_bills"],
    ),
    _record(
        AssetType.INDUSTRIAL_FACILITY,
        source_key="eia_mecs_sector_benchmark",
        source_name="EIA MECS sector benchmark",
        layer=SourceLayer.BENCHMARK,
        access_method=AccessMethod.DOWNLOAD,
        fields=["sector_energy_intensity", "fuel_mix", "benchmark_family"],
        authority=AuthorityTier.HIGH,
        update_frequency="multi-year",
        use="sectoral benchmark and plausibility framing only",
        limitations="Never local plant truth.",
        priority=RoutingPriority.OPTIONAL,
        disallowed_as_substitute_for=["site_eui", "plant_energy_baseline", "fuel_profile"],
    ),
    _record(
        AssetType.INDUSTRIAL_FACILITY,
        source_key="doe_iac_database",
        source_name="DOE IAC database",
        layer=SourceLayer.BENCHMARK,
        access_method=AccessMethod.DOWNLOAD,
        fields=["measure_family", "industrial_case_examples", "typical_savings"],
        authority=AuthorityTier.MEDIUM,
        update_frequency="periodic",
        use="industrial hypothesis generation and idea library",
        limitations="Case library only.",
        priority=RoutingPriority.OPTIONAL,
        disallowed_as_substitute_for=["site_specific_savings", "plant_capex"],
    ),
    _record(
        AssetType.INDUSTRIAL_FACILITY,
        source_key="openei_industrial_combustion",
        source_name="OpenEI industrial combustion context",
        layer=SourceLayer.BENCHMARK,
        access_method=AccessMethod.WEB_PAGE,
        fields=["combustion_archetype", "fuel_context"],
        authority=AuthorityTier.MEDIUM,
        update_frequency="periodic",
        use="supplementary combustion benchmark context",
        limitations="Archetype only; not plant truth.",
        priority=RoutingPriority.OPTIONAL,
        disallowed_as_substitute_for=["boiler_inventory", "site_fuel_profile"],
    ),
]
