from __future__ import annotations

from ..schemas import (
    AccessMethod,
    AssetType,
    AuthorityTier,
    RoutingPriority,
    SourceLayer,
    SourceRegistryRecord,
    SourceRoutingEntry,
)


def _record(
    asset_type: AssetType,
    *,
    source_key: str,
    source_name: str,
    layer: SourceLayer,
    access_method: AccessMethod,
    fields: list[str],
    authority: AuthorityTier,
    update_frequency: str,
    use: str,
    limitations: str,
    priority: RoutingPriority,
    disallowed_as_substitute_for: list[str] | None = None,
) -> SourceRegistryRecord:
    return SourceRegistryRecord(
        jurisdiction="US-NY-NYC",
        asset_type=asset_type,
        source=SourceRoutingEntry(
            source_key=source_key,
            source_name=source_name,
            layer=layer,
            access_method=access_method,
            fields=fields,
            authority=authority,
            update_frequency=update_frequency,
            use=use,
            limitations=limitations,
            priority=priority,
            disallowed_as_substitute_for=list(disallowed_as_substitute_for or []),
        ),
    )


NYC_SOURCE_REGISTRY: list[SourceRegistryRecord] = []

for building_asset_type in (
    AssetType.COMMERCIAL_BUILDING,
    AssetType.MULTIFAMILY,
    AssetType.DATA_CENTER,
):
    NYC_SOURCE_REGISTRY.extend(
        [
            _record(
                building_asset_type,
                source_key="nyc_dof_property_record",
                source_name="NYC Department of Finance / BBL property record",
                layer=SourceLayer.PROPERTY,
                access_method=AccessMethod.PORTAL,
                fields=["address", "owner", "parcel_id", "building_id", "site_boundary"],
                authority=AuthorityTier.HIGH,
                update_frequency="continuous",
                use="primary parcel and address confirmation anchor",
                limitations="Property anchor only; does not by itself provide energy or systems truth.",
                priority=RoutingPriority.MANDATORY,
                disallowed_as_substitute_for=["entity_page", "portfolio_property_list"],
            ),
            _record(
                building_asset_type,
                source_key="nyc_pluto_property",
                source_name="NYC PLUTO property dataset",
                layer=SourceLayer.PROPERTY,
                access_method=AccessMethod.API,
                fields=["GFA", "year_built", "use", "owner", "lot_area", "stories"],
                authority=AuthorityTier.HIGH,
                update_frequency="periodic",
                use="official building scale, use, and property context",
                limitations="Public land-use dataset; does not confirm current systems or utility billing.",
                priority=RoutingPriority.MANDATORY,
                disallowed_as_substitute_for=["brochure_area", "benchmark_proxy_area"],
            ),
            _record(
                building_asset_type,
                source_key="nyc_ll84_energy_benchmarking",
                source_name="NYC LL84 benchmarking dataset",
                layer=SourceLayer.ENERGY,
                access_method=AccessMethod.API,
                fields=["current_EUI", "emissions", "electricity_consumption", "gas_consumption", "energy_star_score"],
                authority=AuthorityTier.HIGH,
                update_frequency="annual",
                use="asset-specific public energy baseline when the building is covered",
                limitations="Covered-building dataset; missing records should degrade to blocked or proxy states rather than be filled from benchmarks.",
                priority=RoutingPriority.MANDATORY,
                disallowed_as_substitute_for=["CBECS_EUI", "energy_star_public_profile", "owner_esg_intensity"],
            ),
            _record(
                building_asset_type,
                source_key="nyc_ll97_covered_buildings_list",
                source_name="NYC LL97 Covered Buildings List",
                layer=SourceLayer.REGULATORY,
                access_method=AccessMethod.FILE_EXPORT,
                fields=["building_id", "regulated_floor_area", "applicable_rule_family", "compliance_period"],
                authority=AuthorityTier.HIGH,
                update_frequency="periodic",
                use="covered-building applicability and regulated-floor-area screening",
                limitations="Screening and coverage context only; not a certified compliance filing.",
                priority=RoutingPriority.MANDATORY,
                disallowed_as_substitute_for=["jurisdiction_only_rule_guess"],
            ),
            _record(
                building_asset_type,
                source_key="nyc_dob_permits",
                source_name="NYC DOB permits and filings",
                layer=SourceLayer.PERMIT,
                access_method=AccessMethod.API,
                fields=["permit_types", "major_renovations", "systems_clues", "capital_activity"],
                authority=AuthorityTier.HIGH,
                update_frequency="continuous",
                use="systems clues, renovation chronology, and filing activity",
                limitations="Permit presence is not equivalent to a verified current systems inventory.",
                priority=RoutingPriority.MANDATORY,
                disallowed_as_substitute_for=["verified_hvac_inventory", "utility_baseline"],
            ),
            _record(
                building_asset_type,
                source_key="nyc_ll97_filing_guidance",
                source_name="NYC LL97 filing guidance / BEAM process",
                layer=SourceLayer.REGULATORY,
                access_method=AccessMethod.WEB_PAGE,
                fields=["article_320_321_path", "beam_process", "compliance_period"],
                authority=AuthorityTier.HIGH,
                update_frequency="periodic",
                use="official filing process and upgrade path context",
                limitations="Guidance only; not building-level filing confirmation.",
                priority=RoutingPriority.HIGH_PRIORITY,
                disallowed_as_substitute_for=["certified_ll97_filing"],
            ),
            _record(
                building_asset_type,
                source_key="nyc_energy_star_annual_score",
                source_name="NYC ENERGY STAR annual score extract",
                layer=SourceLayer.ENERGY,
                access_method=AccessMethod.API,
                fields=["energy_star_score", "current_EUI"],
                authority=AuthorityTier.MEDIUM,
                update_frequency="annual",
                use="secondary public benchmarking clue aligned with NYC disclosure",
                limitations="Secondary to LL84 and not a substitute when LL84 exists.",
                priority=RoutingPriority.OPTIONAL,
                disallowed_as_substitute_for=["nyc_ll84_energy_benchmarking"],
            ),
            _record(
                building_asset_type,
                source_key="nyc_accelerator_program",
                source_name="NYC Accelerator guidance",
                layer=SourceLayer.REGULATORY,
                access_method=AccessMethod.WEB_PAGE,
                fields=["program_guidance", "measure_family_context"],
                authority=AuthorityTier.MEDIUM,
                update_frequency="periodic",
                use="optional advisory context for upgrade pathways",
                limitations="Advisory content only; not asset truth.",
                priority=RoutingPriority.OPTIONAL,
                disallowed_as_substitute_for=["asset_level_capex", "verified_systems_inventory"],
            ),
        ]
    )
