"""Deterministic implementation of motor_030.

Synthetic Data Generation Engine emits reproducible synthetic datasets from an
approved expert problem spec. It validates expert approval, critical ambiguity,
version lineage, parameter constraints, epistemic flags, and output consistency.
It does not call AI services, produce evidence, train ML models, or replace
validation and verification bridges.
"""

from __future__ import annotations

from copy import deepcopy
from datetime import datetime, timezone
import hashlib
import json
import re
from typing import Any, Iterable

try:
    from .errors import (
        ConstraintDriftError,
        CriticalAmbiguityUnresolvedError,
        EpistemicFlagMissingError,
        GeneratorVersionUnresolvedError,
        InvalidParameterConstraintError,
        LineageBreakError,
        Motor030Rejection,
        SpecNotApprovedError,
    )
    from .models import (
        FORBIDDEN_USES,
        INTENDED_USE,
        MOTOR_ID,
        NON_EVIDENTIARY_FLAG,
        SYNTHETIC_DATA_FLAG,
        GenerationManifest,
        GenerationResult,
        SyntheticDataset,
        SyntheticGenerationRun,
    )
except ImportError:  # pragma: no cover - supports direct execution from codebase/
    from errors import (
        ConstraintDriftError,
        CriticalAmbiguityUnresolvedError,
        EpistemicFlagMissingError,
        GeneratorVersionUnresolvedError,
        InvalidParameterConstraintError,
        LineageBreakError,
        Motor030Rejection,
        SpecNotApprovedError,
    )
    from models import (
        FORBIDDEN_USES,
        INTENDED_USE,
        MOTOR_ID,
        NON_EVIDENTIARY_FLAG,
        SYNTHETIC_DATA_FLAG,
        GenerationManifest,
        GenerationResult,
        SyntheticDataset,
        SyntheticGenerationRun,
    )


SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$")
CURRENT_VERSION_STATUSES = {"current", "active", "approved", "released"}
GENERATOR_COMPONENTS = {
    "synthetic_generator",
    "motor_030",
    "synthetic_data_generation_engine",
    "synthetic-data-generation-engine",
}
RESOLVED_STATUSES = {"resolved", "closed", "accepted", "approved"}
LIMITATIONS_NOTE = (
    "Synthetic data generated by motor_030 for exploration only; it is "
    "non-evidentiary and cannot replace Validation Data Bridge or "
    "Verification Bridge."
)


class SyntheticDataGenerationEngine:
    """Core deterministic motor_030 implementation."""

    def generate(
        self,
        *,
        expert_problem_spec: dict[str, Any],
        version_records: list[dict[str, Any]],
        parameter_set: dict[str, Any] | None = None,
        produced_at: str | None = None,
    ) -> dict[str, Any]:
        """Generate or structurally reject motor_030 outputs."""

        emitted_at = produced_at or self._now()
        spec_for_rejection = (
            deepcopy(expert_problem_spec)
            if isinstance(expert_problem_spec, dict)
            else {}
        )
        raw_parameter_set = (
            deepcopy(parameter_set) if isinstance(parameter_set, dict) else parameter_set
        )
        generator_version: str | None = None
        version_record_refs: list[str] = []

        try:
            if not isinstance(expert_problem_spec, dict):
                raise InvalidParameterConstraintError(
                    "expert_problem_spec must be an object",
                    {"field": "expert_problem_spec"},
                )
            if not isinstance(version_records, list):
                raise GeneratorVersionUnresolvedError(
                    "version_records must be a list",
                    {"field": "version_records"},
                )

            spec = deepcopy(expert_problem_spec)
            self._validate_spec_approved(spec)
            self._reject_unresolved_critical_ambiguity(spec)
            generator_version, version_record_refs = self._resolve_generator_version(
                version_records
            )
            constraints = self._constraints_from_spec(spec)
            normalized_parameter_set = self._normalize_parameter_set(
                spec=spec,
                explicit_parameter_set=parameter_set,
            )
            scenario_refs, scenario_column = self._scenario_refs(
                spec=spec,
                parameter_set=normalized_parameter_set,
            )
            records = self._generate_records(
                constraints=constraints,
                sample_size=normalized_parameter_set["sample_size"],
                seed=normalized_parameter_set["generation_seed"],
                scenario_refs=scenario_refs,
                scenario_column=scenario_column,
            )
            quality_checks = self._quality_checks(
                records=records,
                constraints=constraints,
                expected_count=normalized_parameter_set["sample_size"],
                scenario_refs=scenario_refs,
                scenario_column=scenario_column,
            )
            if quality_checks["constraint_violations"]:
                raise ConstraintDriftError(
                    "generated records violated declared constraints",
                    {"quality_checks": quality_checks},
                )

            return self._success_result(
                spec=spec,
                generator_version=generator_version,
                version_record_refs=version_record_refs,
                parameter_set=normalized_parameter_set,
                constraints=constraints,
                scenario_refs=scenario_refs,
                scenario_column=scenario_column,
                records=records,
                quality_checks=quality_checks,
                produced_at=emitted_at,
            ).to_dict()
        except Motor030Rejection as rejection:
            return self._rejection_result(
                spec=spec_for_rejection,
                parameter_set=raw_parameter_set,
                generator_version=generator_version,
                version_record_refs=version_record_refs,
                rejection_code=rejection.rejection_code,
                produced_at=emitted_at,
                details=rejection.details,
            ).to_dict()

    def _success_result(
        self,
        *,
        spec: dict[str, Any],
        generator_version: str,
        version_record_refs: list[str],
        parameter_set: dict[str, Any],
        constraints: list[dict[str, Any]],
        scenario_refs: list[str],
        scenario_column: str | None,
        records: list[dict[str, Any]],
        quality_checks: dict[str, Any],
        produced_at: str,
    ) -> GenerationResult:
        expert_spec_ref = self._required_string(spec, "spec_id")
        source_problem_ref = self._required_string(spec, "source_problem_ref")
        domain_validity_limits = self._domain_validity_limits(spec)
        limitations_note = self._limitations_note(spec)
        constraint_summary = self._constraint_summary(constraints)

        run_identity = {
            "motor": MOTOR_ID,
            "expert_spec_ref": expert_spec_ref,
            "source_problem_ref": source_problem_ref,
            "generator_version": generator_version,
            "version_record_refs": version_record_refs,
            "parameter_set": parameter_set,
            "generation_seed": parameter_set["generation_seed"],
        }
        run_id = self._stable_label("sgr", run_identity)
        schema = self._dataset_schema(constraints, scenario_column, scenario_refs)
        dataset_hash = self._stable_hash(
            {
                "run_id": run_id,
                "schema": schema,
                "records": records,
                "parameter_set": parameter_set,
                "flags": self._epistemic_payload(),
                "lineage": {
                    "expert_spec_ref": expert_spec_ref,
                    "source_problem_ref": source_problem_ref,
                    "generator_version": generator_version,
                    "version_record_refs": version_record_refs,
                },
            }
        )
        dataset_id = self._stable_label(
            "sd",
            {"run_id": run_id, "dataset_hash": dataset_hash, "schema": schema},
        )
        fingerprint = self._stable_hash(
            {
                "run_identity": run_identity,
                "dataset_id": dataset_id,
                "dataset_hash": dataset_hash,
                "quality_checks": quality_checks,
            }
        )
        manifest_id = self._stable_label(
            "gm",
            {
                "run_id": run_id,
                "dataset_refs": [dataset_id],
                "generator_version": generator_version,
                "parameter_set": parameter_set,
                "reproducibility_fingerprint": fingerprint,
            },
        )

        run = SyntheticGenerationRun(
            run_id=run_id,
            record_id=self._stable_label("sgr_rec", {"run_id": run_id}),
            expert_spec_ref=expert_spec_ref,
            source_problem_ref=source_problem_ref,
            generator_version=generator_version,
            version_record_refs=version_record_refs,
            parameter_set=parameter_set,
            generation_seed=parameter_set["generation_seed"],
            scenario_refs=scenario_refs,
            status="generated",
            rejection_code=None,
            constraint_summary=constraint_summary,
            synthetic_data_flag=SYNTHETIC_DATA_FLAG,
            non_evidentiary_flag=NON_EVIDENTIARY_FLAG,
            intended_use=INTENDED_USE,
            domain_validity_limits=domain_validity_limits,
            limitations_note=limitations_note,
            source_ref=source_problem_ref,
            produced_by_motor=MOTOR_ID,
            produced_at=produced_at,
            parent_id=None,
            version_id=self._stable_label("sgr_v", {"run_id": run_id, "status": "generated"}),
            created_at=produced_at,
            updated_at=produced_at,
            version_hash=self._stable_hash(
                {
                    **run_identity,
                    "scenario_refs": scenario_refs,
                    "status": "generated",
                    "rejection_code": None,
                    "constraint_summary": constraint_summary,
                    "flags": self._epistemic_payload(),
                    "parent_id": None,
                }
            ),
        )

        dataset = SyntheticDataset(
            dataset_id=dataset_id,
            record_id=self._stable_label("sd_rec", {"dataset_id": dataset_id}),
            run_id=run_id,
            manifest_id=manifest_id,
            expert_spec_ref=expert_spec_ref,
            source_problem_ref=source_problem_ref,
            generator_version=generator_version,
            version_record_refs=version_record_refs,
            parameter_set=parameter_set,
            schema=schema,
            records=records,
            record_count=len(records),
            partition_refs=[],
            scenario_column=scenario_column,
            dataset_hash=dataset_hash,
            quality_checks=quality_checks,
            synthetic_data_flag=SYNTHETIC_DATA_FLAG,
            non_evidentiary_flag=NON_EVIDENTIARY_FLAG,
            intended_use=INTENDED_USE,
            domain_validity_limits=domain_validity_limits,
            limitations_note=limitations_note,
            source_ref=source_problem_ref,
            produced_by_motor=MOTOR_ID,
            produced_at=produced_at,
            parent_id=None,
            version_id=self._stable_label("sd_v", {"dataset_id": dataset_id}),
            created_at=produced_at,
            updated_at=produced_at,
            version_hash=self._stable_hash(
                {
                    "dataset_id": dataset_id,
                    "run_id": run_id,
                    "manifest_id": manifest_id,
                    "schema": schema,
                    "records": records,
                    "record_count": len(records),
                    "dataset_hash": dataset_hash,
                    "quality_checks": quality_checks,
                    "flags": self._epistemic_payload(),
                    "lineage": run_identity,
                    "parent_id": None,
                }
            ),
        )

        manifest = GenerationManifest(
            manifest_id=manifest_id,
            record_id=self._stable_label("gm_rec", {"manifest_id": manifest_id}),
            run_id=run_id,
            dataset_refs=[dataset_id],
            expert_spec_ref=expert_spec_ref,
            source_problem_ref=source_problem_ref,
            generator_version=generator_version,
            version_record_refs=version_record_refs,
            parameter_set=parameter_set,
            constraints_applied=constraints,
            scenario_summary=self._scenario_summary(
                scenario_refs=scenario_refs,
                scenario_column=scenario_column,
                record_count=len(records),
            ),
            quality_checks=quality_checks,
            reproducibility_fingerprint=fingerprint,
            forbidden_uses=list(FORBIDDEN_USES),
            synthetic_data_flag=SYNTHETIC_DATA_FLAG,
            non_evidentiary_flag=NON_EVIDENTIARY_FLAG,
            intended_use=INTENDED_USE,
            domain_validity_limits=domain_validity_limits,
            limitations_note=limitations_note,
            source_ref=source_problem_ref,
            produced_by_motor=MOTOR_ID,
            produced_at=produced_at,
            parent_id=None,
            version_id=self._stable_label("gm_v", {"manifest_id": manifest_id}),
            created_at=produced_at,
            updated_at=produced_at,
            version_hash=self._stable_hash(
                {
                    "manifest_id": manifest_id,
                    "run_id": run_id,
                    "dataset_refs": [dataset_id],
                    "constraints_applied": constraints,
                    "quality_checks": quality_checks,
                    "reproducibility_fingerprint": fingerprint,
                    "forbidden_uses": FORBIDDEN_USES,
                    "flags": self._epistemic_payload(),
                    "lineage": run_identity,
                    "parent_id": None,
                }
            ),
        )

        self._assert_complete_flags(run.to_dict(), dataset.to_dict(), manifest.to_dict())
        self._assert_lineage(run, dataset, manifest)
        return GenerationResult(run, dataset, manifest)

    def _rejection_result(
        self,
        *,
        spec: dict[str, Any],
        parameter_set: Any,
        generator_version: str | None,
        version_record_refs: list[str],
        rejection_code: str,
        produced_at: str,
        details: dict[str, Any],
    ) -> GenerationResult:
        expert_spec_ref = self._optional_string(spec.get("spec_id"))
        source_problem_ref = self._optional_string(spec.get("source_problem_ref"))
        safe_parameter_set = deepcopy(parameter_set) if isinstance(parameter_set, dict) else {}
        generation_seed = (
            safe_parameter_set.get("generation_seed")
            if self._is_int(safe_parameter_set.get("generation_seed"))
            else safe_parameter_set.get("seed")
            if self._is_int(safe_parameter_set.get("seed"))
            else None
        )
        domain_validity_limits = self._domain_validity_limits(
            spec, fallback="Rejected before domain validity could be established."
        )
        limitations_note = self._limitations_note(spec)
        run_identity = {
            "motor": MOTOR_ID,
            "expert_spec_ref": expert_spec_ref,
            "source_problem_ref": source_problem_ref,
            "generator_version": generator_version,
            "version_record_refs": version_record_refs,
            "parameter_set": safe_parameter_set,
            "generation_seed": generation_seed,
            "status": "rejected",
            "rejection_code": rejection_code,
            "details": details,
        }
        run_id = self._stable_label("sgr_rejected", run_identity)
        run = SyntheticGenerationRun(
            run_id=run_id,
            record_id=self._stable_label("sgr_rec", {"run_id": run_id}),
            expert_spec_ref=expert_spec_ref,
            source_problem_ref=source_problem_ref,
            generator_version=generator_version,
            version_record_refs=version_record_refs,
            parameter_set=safe_parameter_set,
            generation_seed=generation_seed,
            scenario_refs=[],
            status="rejected",
            rejection_code=rejection_code,
            constraint_summary={"status": "not_applied", "rejection_details": details},
            synthetic_data_flag=SYNTHETIC_DATA_FLAG,
            non_evidentiary_flag=NON_EVIDENTIARY_FLAG,
            intended_use=INTENDED_USE,
            domain_validity_limits=domain_validity_limits,
            limitations_note=limitations_note,
            source_ref=source_problem_ref,
            produced_by_motor=MOTOR_ID,
            produced_at=produced_at,
            parent_id=None,
            version_id=self._stable_label("sgr_v", run_identity),
            created_at=produced_at,
            updated_at=produced_at,
            version_hash=self._stable_hash(
                {
                    **run_identity,
                    "constraint_summary": {
                        "status": "not_applied",
                        "rejection_details": details,
                    },
                    "flags": self._epistemic_payload(),
                    "parent_id": None,
                }
            ),
        )
        self._assert_complete_flags(run.to_dict())
        return GenerationResult(run, None, None)

    def _validate_spec_approved(self, spec: dict[str, Any]) -> None:
        spec_id = self._optional_string(spec.get("spec_id"))
        source_problem_ref = self._optional_string(spec.get("source_problem_ref"))
        status = str(spec.get("status", "")).strip().lower()
        handoff_allowed = spec.get("handoff_allowed")
        if not spec_id or not source_problem_ref:
            raise SpecNotApprovedError(
                "expert_problem_spec must include spec_id and source_problem_ref",
                {"spec_id": spec_id, "source_problem_ref": source_problem_ref},
            )
        if status != "approved" or handoff_allowed is not True:
            raise SpecNotApprovedError(
                "expert_problem_spec is not approved for handoff",
                {"status": spec.get("status"), "handoff_allowed": handoff_allowed},
            )
        if not self._has_approved_review(spec):
            raise SpecNotApprovedError(
                "expert_problem_spec lacks approved expert review evidence",
                {
                    "review_status": spec.get("review_status"),
                    "expert_review": spec.get("expert_review"),
                },
            )

    def _has_approved_review(self, spec: dict[str, Any]) -> bool:
        if str(spec.get("review_status", "")).strip().lower() == "approved":
            return True
        if spec.get("expert_review_approved") is True:
            return True
        for key in ("expert_review", "review", "expert_revision"):
            review = spec.get(key)
            if isinstance(review, dict):
                if str(review.get("status", "")).strip().lower() == "approved":
                    return True
                if review.get("approved") is True:
                    return True
        if spec.get("approved_by") and spec.get("approved_at"):
            return True
        return False

    def _reject_unresolved_critical_ambiguity(self, spec: dict[str, Any]) -> None:
        register = spec.get("ambiguity_register", [])
        if isinstance(register, dict) and register.get("has_unresolved_critical") is True:
            raise CriticalAmbiguityUnresolvedError(
                "ambiguity register has unresolved critical ambiguity",
                {"ambiguity_register_ref": register.get("register_id")},
            )
        items = register.get("items", []) if isinstance(register, dict) else register
        if items is None:
            items = []
        if not isinstance(items, list):
            raise InvalidParameterConstraintError(
                "ambiguity_register must be a list or object with items",
                {"field": "ambiguity_register"},
            )
        for item in items:
            if not isinstance(item, dict):
                raise InvalidParameterConstraintError(
                    "ambiguity item must be an object",
                    {"item": item},
                )
            impact = str(item.get("impact_if_unresolved", "")).strip().lower()
            status = str(item.get("resolution_status", "")).strip().lower()
            resolved = item.get("resolved")
            is_resolved = resolved is True or status in RESOLVED_STATUSES
            if impact == "critical" and not is_resolved:
                raise CriticalAmbiguityUnresolvedError(
                    "critical ambiguity is unresolved",
                    {"ambiguity_id": item.get("ambiguity_id")},
                )

    def _resolve_generator_version(
        self,
        version_records: list[dict[str, Any]],
    ) -> tuple[str, list[str]]:
        for record in version_records:
            if not isinstance(record, dict):
                continue
            status = str(
                record.get("status")
                or record.get("state")
                or record.get("version_status")
                or ""
            ).strip().lower()
            metadata = record.get("metadata") if isinstance(record.get("metadata"), dict) else {}
            component = str(
                record.get("component")
                or record.get("component_id")
                or record.get("object_ref")
                or record.get("object_type")
                or metadata.get("component")
                or metadata.get("component_id")
                or ""
            ).strip().lower()
            component = component.replace(" ", "_")
            is_generator = (
                component in GENERATOR_COMPONENTS
                or ("synthetic" in component and "generator" in component)
            )
            if status not in CURRENT_VERSION_STATUSES or not is_generator:
                continue
            version = self._optional_string(
                record.get("generator_version")
                or record.get("version")
                or record.get("semantic_version")
                or metadata.get("generator_version")
                or metadata.get("version")
            )
            if version and SEMVER_RE.match(version):
                return version, [self._version_record_ref(record)]
        raise GeneratorVersionUnresolvedError(
            "no current semver generator_version resolved from version_records",
            {"version_record_count": len(version_records)},
        )

    def _constraints_from_spec(self, spec: dict[str, Any]) -> list[dict[str, Any]]:
        raw_constraints = (
            spec.get("variables")
            or spec.get("variable_constraints")
            or spec.get("parameter_constraints")
            or spec.get("constraints")
        )
        if not isinstance(raw_constraints, list) or not raw_constraints:
            raise InvalidParameterConstraintError(
                "expert_problem_spec must declare variables with verifiable domains",
                {"field": "variables"},
            )

        constraints: list[dict[str, Any]] = []
        seen_names: set[str] = set()
        for raw in raw_constraints:
            if not isinstance(raw, dict):
                raise InvalidParameterConstraintError(
                    "variable constraint must be an object",
                    {"constraint": raw},
                )
            name = self._first_string(
                raw,
                ("name", "variable_name", "parameter_name", "field", "column"),
            )
            value_type = self._first_string(raw, ("type", "value_type", "data_type")).lower()
            if not name or not value_type:
                raise InvalidParameterConstraintError(
                    "variable constraint must include name and type",
                    {"constraint": raw},
                )
            if name in seen_names:
                raise InvalidParameterConstraintError(
                    "variable names must be unique",
                    {"variable_name": name},
                )
            seen_names.add(name)
            domain = raw.get("allowed_domain") if isinstance(raw.get("allowed_domain"), dict) else {}
            nullable = raw.get("nullable", False)
            if not isinstance(nullable, bool):
                raise InvalidParameterConstraintError(
                    "nullable must be boolean when present",
                    {"variable_name": name, "nullable": nullable},
                )

            if value_type in {"number", "numeric", "float"}:
                min_value, max_value = self._numeric_range(raw, domain, name)
                constraints.append(
                    {
                        "name": name,
                        "type": "number",
                        "min": min_value,
                        "max": max_value,
                        "nullable": nullable,
                    }
                )
            elif value_type in {"integer", "int"}:
                min_value, max_value = self._numeric_range(raw, domain, name)
                if not self._is_int(min_value) or not self._is_int(max_value):
                    raise InvalidParameterConstraintError(
                        "integer variables require integer min and max",
                        {"variable_name": name},
                    )
                constraints.append(
                    {
                        "name": name,
                        "type": "integer",
                        "min": int(min_value),
                        "max": int(max_value),
                        "nullable": nullable,
                    }
                )
            elif value_type in {"category", "categorical", "enum", "string"}:
                allowed_values = self._allowed_values(raw, domain, name)
                constraints.append(
                    {
                        "name": name,
                        "type": "category",
                        "allowed_values": allowed_values,
                        "nullable": nullable,
                    }
                )
            elif value_type == "boolean":
                constraints.append({"name": name, "type": "boolean", "nullable": nullable})
            else:
                raise InvalidParameterConstraintError(
                    "unsupported variable type",
                    {"variable_name": name, "type": value_type},
                )
        return constraints

    def _numeric_range(
        self,
        raw: dict[str, Any],
        domain: dict[str, Any],
        name: str,
    ) -> tuple[int | float, int | float]:
        range_value = raw.get("range", domain.get("range"))
        if isinstance(range_value, list) and len(range_value) == 2:
            min_value, max_value = range_value
        else:
            min_value = raw.get("min", raw.get("minimum", domain.get("min", domain.get("minimum"))))
            max_value = raw.get("max", raw.get("maximum", domain.get("max", domain.get("maximum"))))
        if not self._is_number(min_value) or not self._is_number(max_value):
            raise InvalidParameterConstraintError(
                "numeric variable requires numeric min and max",
                {"variable_name": name, "min": min_value, "max": max_value},
            )
        if min_value > max_value:
            raise InvalidParameterConstraintError(
                "numeric variable min cannot exceed max",
                {"variable_name": name, "min": min_value, "max": max_value},
            )
        return min_value, max_value

    def _allowed_values(
        self,
        raw: dict[str, Any],
        domain: dict[str, Any],
        name: str,
    ) -> list[Any]:
        values = (
            raw.get("allowed_values")
            or raw.get("categories")
            or raw.get("values")
            or domain.get("allowed_values")
            or domain.get("categories")
            or domain.get("values")
        )
        if not isinstance(values, list) or not values:
            raise InvalidParameterConstraintError(
                "category variable requires non-empty allowed_values",
                {"variable_name": name},
            )
        for value in values:
            if isinstance(value, (dict, list)):
                raise InvalidParameterConstraintError(
                    "category values must be scalar",
                    {"variable_name": name, "value": value},
                )
        return deepcopy(values)

    def _normalize_parameter_set(
        self,
        *,
        spec: dict[str, Any],
        explicit_parameter_set: dict[str, Any] | None,
    ) -> dict[str, Any]:
        raw = (
            explicit_parameter_set
            if explicit_parameter_set is not None
            else spec.get("parameter_set")
            or spec.get("generation_parameters")
            or spec.get("default_parameter_set")
        )
        if not isinstance(raw, dict):
            raise InvalidParameterConstraintError(
                "parameter_set must be provided as an object",
                {"field": "parameter_set"},
            )
        parameter_set = deepcopy(raw)
        sample_size = parameter_set.get("sample_size")
        seed = parameter_set.get("seed", parameter_set.get("generation_seed"))
        sampling_strategy = self._optional_string(parameter_set.get("sampling_strategy"))
        if not self._is_int(sample_size) or sample_size < 1:
            raise InvalidParameterConstraintError(
                "parameter_set.sample_size must be a positive integer",
                {"sample_size": sample_size},
            )
        if not self._is_int(seed):
            raise InvalidParameterConstraintError(
                "parameter_set seed must be an integer",
                {"seed": seed, "generation_seed": parameter_set.get("generation_seed")},
            )
        if not sampling_strategy:
            raise InvalidParameterConstraintError(
                "parameter_set.sampling_strategy must be declared",
                {"sampling_strategy": parameter_set.get("sampling_strategy")},
            )
        parameter_set["sample_size"] = sample_size
        parameter_set["seed"] = seed
        parameter_set["generation_seed"] = seed
        parameter_set["sampling_strategy"] = sampling_strategy
        return parameter_set

    def _scenario_refs(
        self,
        *,
        spec: dict[str, Any],
        parameter_set: dict[str, Any],
    ) -> tuple[list[str], str | None]:
        declared = self._declared_scenarios(spec)
        if "scenarios" in parameter_set:
            raw = parameter_set["scenarios"]
            if not isinstance(raw, list) or not raw:
                raise InvalidParameterConstraintError(
                    "parameter_set.scenarios must be a non-empty list when present",
                    {"scenarios": raw},
                )
            scenario_refs = [self._string_or_reject(value, "parameter_set.scenarios") for value in raw]
        elif "scenario" in parameter_set:
            scenario_refs = [self._string_or_reject(parameter_set["scenario"], "parameter_set.scenario")]
        elif len(declared) > 1:
            scenario_refs = list(declared)
            parameter_set["scenarios"] = list(declared)
        else:
            scenario_refs = []

        if declared:
            invalid = [scenario for scenario in scenario_refs if scenario not in declared]
            if invalid:
                raise InvalidParameterConstraintError(
                    "parameter_set requested scenario not declared by spec",
                    {"invalid_scenarios": invalid, "declared_scenarios": declared},
                )
        scenario_column = "scenario" if len(scenario_refs) > 1 else None
        return scenario_refs, scenario_column

    def _declared_scenarios(self, spec: dict[str, Any]) -> list[str]:
        raw = spec.get("scenarios") or spec.get("allowed_scenarios") or []
        if raw is None:
            return []
        if not isinstance(raw, list):
            raise InvalidParameterConstraintError(
                "scenarios must be a list when present",
                {"scenarios": raw},
            )
        scenarios: list[str] = []
        for item in raw:
            if isinstance(item, str):
                value = item.strip()
            elif isinstance(item, dict):
                value = self._first_string(item, ("scenario_id", "id", "name", "ref"))
            else:
                value = ""
            if not value:
                raise InvalidParameterConstraintError(
                    "scenario entries must have stable string identifiers",
                    {"scenario": item},
                )
            if value not in scenarios:
                scenarios.append(value)
        return scenarios

    def _generate_records(
        self,
        *,
        constraints: list[dict[str, Any]],
        sample_size: int,
        seed: int,
        scenario_refs: list[str],
        scenario_column: str | None,
    ) -> list[dict[str, Any]]:
        records: list[dict[str, Any]] = []
        for index in range(sample_size):
            scenario = (
                scenario_refs[index % len(scenario_refs)]
                if scenario_refs and scenario_column
                else None
            )
            record: dict[str, Any] = {}
            if scenario is not None and scenario_column is not None:
                record[scenario_column] = scenario
            for constraint in constraints:
                record[constraint["name"]] = self._value_for_constraint(
                    constraint=constraint,
                    seed=seed,
                    index=index,
                    scenario=scenario,
                )
            records.append(record)
        return records

    def _value_for_constraint(
        self,
        *,
        constraint: dict[str, Any],
        seed: int,
        index: int,
        scenario: str | None,
    ) -> Any:
        value_type = constraint["type"]
        fraction = self._stable_fraction(
            {
                "seed": seed,
                "index": index,
                "scenario": scenario,
                "variable": constraint["name"],
            }
        )
        if value_type == "number":
            min_value = constraint["min"]
            max_value = constraint["max"]
            if min_value == max_value:
                return min_value
            return round(min_value + (max_value - min_value) * fraction, 6)
        if value_type == "integer":
            min_value = constraint["min"]
            max_value = constraint["max"]
            if min_value == max_value:
                return min_value
            span = max_value - min_value + 1
            return min_value + min(int(fraction * span), span - 1)
        if value_type == "category":
            values = constraint["allowed_values"]
            return values[min(int(fraction * len(values)), len(values) - 1)]
        if value_type == "boolean":
            return fraction >= 0.5
        raise InvalidParameterConstraintError(
            "unsupported constraint type during generation",
            {"constraint": constraint},
        )

    def _quality_checks(
        self,
        *,
        records: list[dict[str, Any]],
        constraints: list[dict[str, Any]],
        expected_count: int,
        scenario_refs: list[str],
        scenario_column: str | None,
    ) -> dict[str, Any]:
        violations: list[dict[str, Any]] = []
        if len(records) != expected_count:
            violations.append(
                {
                    "type": "record_count",
                    "expected": expected_count,
                    "actual": len(records),
                }
            )
        for index, record in enumerate(records):
            if scenario_column is not None:
                scenario_value = record.get(scenario_column)
                if scenario_value not in scenario_refs:
                    violations.append(
                        {
                            "type": "scenario",
                            "row_index": index,
                            "field": scenario_column,
                            "value": scenario_value,
                        }
                    )
            for constraint in constraints:
                value = record.get(constraint["name"])
                violations.extend(self._violations_for_value(index, constraint, value))
        return {
            "status": "pass" if not violations else "fail",
            "record_count_matches": len(records) == expected_count,
            "type_violations": [
                violation for violation in violations if violation["type"] == "type"
            ],
            "range_violations": [
                violation for violation in violations if violation["type"] == "range"
            ],
            "category_violations": [
                violation for violation in violations if violation["type"] == "category"
            ],
            "constraint_violations": violations,
            "reproducibility_check": "deterministic_hash_inputs",
        }

    def _violations_for_value(
        self,
        index: int,
        constraint: dict[str, Any],
        value: Any,
    ) -> list[dict[str, Any]]:
        name = constraint["name"]
        value_type = constraint["type"]
        violations: list[dict[str, Any]] = []
        if value_type == "number":
            if not self._is_number(value):
                violations.append({"type": "type", "row_index": index, "field": name, "value": value})
            elif value < constraint["min"] or value > constraint["max"]:
                violations.append({"type": "range", "row_index": index, "field": name, "value": value})
        elif value_type == "integer":
            if not self._is_int(value):
                violations.append({"type": "type", "row_index": index, "field": name, "value": value})
            elif value < constraint["min"] or value > constraint["max"]:
                violations.append({"type": "range", "row_index": index, "field": name, "value": value})
        elif value_type == "category":
            if value not in constraint["allowed_values"]:
                violations.append({"type": "category", "row_index": index, "field": name, "value": value})
        elif value_type == "boolean":
            if not isinstance(value, bool):
                violations.append({"type": "type", "row_index": index, "field": name, "value": value})
        return violations

    def _dataset_schema(
        self,
        constraints: list[dict[str, Any]],
        scenario_column: str | None,
        scenario_refs: list[str],
    ) -> dict[str, Any]:
        columns: list[dict[str, Any]] = []
        if scenario_column is not None:
            columns.append(
                {
                    "name": scenario_column,
                    "type": "category",
                    "allowed_values": list(scenario_refs),
                    "nullable": False,
                }
            )
        columns.extend(deepcopy(constraints))
        return {"columns": columns}

    def _constraint_summary(self, constraints: list[dict[str, Any]]) -> dict[str, Any]:
        return {
            "variable_count": len(constraints),
            "variables": [constraint["name"] for constraint in constraints],
            "constraints": deepcopy(constraints),
        }

    def _scenario_summary(
        self,
        *,
        scenario_refs: list[str],
        scenario_column: str | None,
        record_count: int,
    ) -> dict[str, Any]:
        if not scenario_refs:
            return {
                "mode": "implicit_single_scenario",
                "scenario_refs": [],
                "scenario_column": None,
                "record_count": record_count,
            }
        if scenario_column is None:
            return {
                "mode": "single_declared_scenario",
                "scenario_refs": scenario_refs,
                "scenario_column": None,
                "record_count": record_count,
            }
        base = record_count // len(scenario_refs)
        extra = record_count % len(scenario_refs)
        counts = {
            scenario: base + (1 if position < extra else 0)
            for position, scenario in enumerate(scenario_refs)
        }
        return {
            "mode": "declared_scenarios",
            "scenario_refs": scenario_refs,
            "scenario_column": scenario_column,
            "record_counts_by_scenario": counts,
            "record_count": record_count,
        }

    def _assert_complete_flags(self, *objects: dict[str, Any]) -> None:
        required_fields = {
            "synthetic_data_flag": True,
            "non_evidentiary_flag": True,
            "intended_use": INTENDED_USE,
        }
        for obj in objects:
            for field, expected in required_fields.items():
                if obj.get(field) != expected:
                    raise EpistemicFlagMissingError(
                        "output is missing required epistemic flag",
                        {"field": field, "expected": expected},
                    )
            if not self._optional_string(obj.get("domain_validity_limits")):
                raise EpistemicFlagMissingError(
                    "output is missing domain_validity_limits",
                    {"object_id": obj.get("run_id") or obj.get("dataset_id") or obj.get("manifest_id")},
                )
            if not self._optional_string(obj.get("limitations_note")):
                raise EpistemicFlagMissingError(
                    "output is missing limitations_note",
                    {"object_id": obj.get("run_id") or obj.get("dataset_id") or obj.get("manifest_id")},
                )

    def _assert_lineage(
        self,
        run: SyntheticGenerationRun,
        dataset: SyntheticDataset,
        manifest: GenerationManifest,
    ) -> None:
        shared_fields = (
            "run_id",
            "expert_spec_ref",
            "source_problem_ref",
            "generator_version",
            "version_record_refs",
            "parameter_set",
        )
        run_payload = run.to_dict()
        dataset_payload = dataset.to_dict()
        manifest_payload = manifest.to_dict()
        for field in shared_fields:
            if dataset_payload.get(field) != run_payload.get(field):
                raise LineageBreakError(
                    "dataset lineage does not match generation run",
                    {"field": field},
                )
            if manifest_payload.get(field) != run_payload.get(field):
                raise LineageBreakError(
                    "manifest lineage does not match generation run",
                    {"field": field},
                )
        if dataset.manifest_id != manifest.manifest_id or dataset.dataset_id not in manifest.dataset_refs:
            raise LineageBreakError(
                "dataset and manifest cross references are inconsistent",
                {"dataset_id": dataset.dataset_id, "manifest_id": manifest.manifest_id},
            )

    def _epistemic_payload(self) -> dict[str, Any]:
        return {
            "synthetic_data_flag": SYNTHETIC_DATA_FLAG,
            "non_evidentiary_flag": NON_EVIDENTIARY_FLAG,
            "intended_use": INTENDED_USE,
        }

    def _domain_validity_limits(
        self,
        spec: dict[str, Any],
        fallback: str = "Synthetic exploration only within the approved expert spec domain.",
    ) -> str:
        return self._optional_string(spec.get("domain_validity_limits")) or fallback

    def _limitations_note(self, spec: dict[str, Any]) -> str:
        note = self._optional_string(spec.get("limitations_note"))
        if note:
            return f"{note} {LIMITATIONS_NOTE}"
        return LIMITATIONS_NOTE

    def _version_record_ref(self, record: dict[str, Any]) -> str:
        return (
            self._optional_string(record.get("version_id"))
            or self._optional_string(record.get("record_id"))
            or self._stable_label("vr", record)
        )

    def _required_string(self, mapping: dict[str, Any], field: str) -> str:
        value = self._optional_string(mapping.get(field))
        if not value:
            raise InvalidParameterConstraintError(
                "required string field is missing",
                {"field": field},
            )
        return value

    def _first_string(self, mapping: dict[str, Any], fields: Iterable[str]) -> str:
        for field in fields:
            value = self._optional_string(mapping.get(field))
            if value:
                return value
        return ""

    def _string_or_reject(self, value: Any, field: str) -> str:
        string_value = self._optional_string(value)
        if not string_value:
            raise InvalidParameterConstraintError(
                "field must be a non-empty string",
                {"field": field, "value": value},
            )
        return string_value

    def _optional_string(self, value: Any) -> str:
        if isinstance(value, str):
            return value.strip()
        return ""

    def _is_int(self, value: Any) -> bool:
        return isinstance(value, int) and not isinstance(value, bool)

    def _is_number(self, value: Any) -> bool:
        return isinstance(value, (int, float)) and not isinstance(value, bool)

    def _stable_fraction(self, payload: Any) -> float:
        digest = self._stable_hash(payload)
        numerator = int(digest[:16], 16)
        denominator = float(16**16 - 1)
        return numerator / denominator

    def _stable_label(self, prefix: str, payload: Any) -> str:
        return f"{prefix}_{self._stable_hash(payload)[:16]}"

    def _stable_hash(self, payload: Any) -> str:
        serialized = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
        return hashlib.sha256(serialized.encode("utf-8")).hexdigest()

    def _now(self) -> str:
        return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def generate_synthetic_data(
    *,
    expert_problem_spec: dict[str, Any],
    version_records: list[dict[str, Any]],
    parameter_set: dict[str, Any] | None = None,
    produced_at: str | None = None,
) -> dict[str, Any]:
    """Convenience entry point for one deterministic motor_030 run."""

    return SyntheticDataGenerationEngine().generate(
        expert_problem_spec=expert_problem_spec,
        version_records=version_records,
        parameter_set=parameter_set,
        produced_at=produced_at,
    )
