[metadata]
name = zlab-taxonomy-canonical-entity-service
version = 0.1.0
description = Taxonomy and canonical entity service for ZLab.

[options]
packages = find:
python_requires = >=3.9

[options.packages.find]
include =
    taxonomy_canonical_entity_service
    taxonomy_canonical_entity_service.*
